site_name: University Courses
site_author: Sario Tedesco
site_description: >
    I wanna go home now...
site_url: https://Raven-s-Soul.github.io/University-Courses/
use_directory_urls: true

theme:
  name: material
  icon:
    logo: fontawesome/solid/book-open
    annotation: material/star-four-points-circle
#  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
  #  - content.footnote.tooltips

  font:
    text: Open Sans
    code: JetBrains Mono

  language: en

  palette:

  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
      accent: deep purple

  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: deep purple


  # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: deep purple

nav:
  - Homepage: index.md
  - Anno I: Year1.md
  - Anno II: Year2.md
  - Anno III: Year3.md
  - Corsi: Corsi.md
  - Programmi utili: Software.md
  - Ringraziamenti: Thanks.md
  # Is required for render the side nav, even if i will hide it later in the partials
  - ExampleTools: ExampleTools.md

not_in_nav: |
  ExampleTools.md

plugins:
  - search
      # exclude:
      #       - ExampleTools.md
  - glightbox
  - minify: # https://github.com/byrnereese/mkdocs-minify-plugin
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - social:
      cards_layout_options:
        background_color: "#4e00ff"
#        background_image: layouts/background.png
#        background_color: transparent
#        logo: docs/assets/logo.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  # - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true


extra_javascript:
  - javascripts/extra.js
#   Tecnicaly you can have both but is slower
#   Math Alternative 1 (Functionality)
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#   Math Alternative 2 (Speed) - note the extra css too
  # - javascripts/katex.js
  # - https://unpkg.com/katex@0/dist/katex.min.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mermaid.mjs

extra_css:
  - stylesheets/extra.css
  # - https://unpkg.com/katex@0/dist/katex.min.css

watch:
  - docs
  - docs/assets
  - docs/javascripts
  - docs/stylesheets
  - overrides
  - overrides/partials

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Raven-s-Soul
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sario-tedesco/
    - icon: fontawesome/solid/envelope
      name: Email
      link: mailto:sariotedesco@gmail.com
    # - icon: /fontawesome/brands/telegram
    #   link: https:/
    # - icon: /fontawesome/brands/discord
    #   link: https://discord.gg/

  # alternate:
  # - name: English
  #   link: /en/
  #   lang: en
  # - name: Italiano
  #   link: /it/
  #   lang: it


copyright: |
  <a href="https://github.com/Raven-s-Soul"  target="_blank" rel="noopener">Sario Tedesco</a>